Telescope.cs(149, 33): error CS1061: 'ASCOM.DriverAccess.MemberFactory' does not contain a definition for 'IsComObject' and no extension method 'IsComObject' accepting a first argument of type 'ASCOM.DriverAccess.MemberFactory' could be found (are you missing a using directive or an assembly reference?)